-- MySQL Script generated by MySQL Workbench
-- Wed Nov 12 19:44:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinUp-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FinUp-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinUp` DEFAULT CHARACTER SET utf8 ;
USE `FinUp` ;

-- -----------------------------------------------------
-- Table `FinUp`.`Pessoa_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`Pessoa_Fisica` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(200) NOT NULL,
  `CPF` VARCHAR(16) NOT NULL,
  `Telefone` INT NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  `Data_Inicio` DATETIME NOT NULL,
  `Data_Fim` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`Tipo_Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`Tipo_Pagamento` (
  `Id` INT NOT NULL,
  `Tipo_Pagamento` ENUM('Cartão de crédito', 'Cartão de débito', 'PIX', 'Boleto', 'Dinheiro', 'Cheque') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`Tipo_Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`Tipo_Gasto` (
  `Id` INT NOT NULL,
  `Tipo_Gasto` ENUM('Crédito', 'Débito') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`Classe_Principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`Classe_Principal` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`SubClasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`SubClasse` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(55) NOT NULL,
  `Classe_Principal_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_SubClasse_Classe_Principal1_idx` (`Classe_Principal_Id` ASC) VISIBLE,
  CONSTRAINT `fk_SubClasse_Classe_Principal1`
    FOREIGN KEY (`Classe_Principal_Id`)
    REFERENCES `FinUp`.`Classe_Principal` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`CNPJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`CNPJ` (
  `Id` INT NOT NULL,
  `Nome_Empresa` VARCHAR(255) NOT NULL,
  `CNPJ` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`Transacao` (
  `Id` INT NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `CNPJ_has_Classe_Principal_Classe_Principal_SubClasse_Id` INT NOT NULL,
  `Pessoa_Fisica_Id` INT NOT NULL,
  `Tipo_Pagamento_Id` INT NOT NULL,
  `Tipo_Gasto_Id` INT NOT NULL,
  `Classe_Principal_SubClasse_Id` INT NOT NULL,
  `SubClasse_Id` INT NOT NULL,
  `CNPJ_Id` INT NOT NULL,
  `Classe_Principal_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `CNPJ_has_Classe_Principal_Classe_Principal_SubClasse_Id`, `Pessoa_Fisica_Id`, `Tipo_Pagamento_Id`, `Tipo_Gasto_Id`, `Classe_Principal_SubClasse_Id`, `SubClasse_Id`, `CNPJ_Id`, `Classe_Principal_Id`),
  INDEX `fk_Transacao_Pessoa_Fisica1_idx` (`Pessoa_Fisica_Id` ASC) VISIBLE,
  INDEX `fk_Transacao_Tipo_Pagamento1_idx` (`Tipo_Pagamento_Id` ASC) VISIBLE,
  INDEX `fk_Transacao_Tipo_Gasto1_idx` (`Tipo_Gasto_Id` ASC) VISIBLE,
  INDEX `fk_Transacao_SubClasse1_idx` (`SubClasse_Id` ASC) VISIBLE,
  INDEX `fk_Transacao_CNPJ1_idx` (`CNPJ_Id` ASC) VISIBLE,
  INDEX `fk_Transacao_Classe_Principal1_idx` (`Classe_Principal_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Transacao_Pessoa_Fisica1`
    FOREIGN KEY (`Pessoa_Fisica_Id`)
    REFERENCES `FinUp`.`Pessoa_Fisica` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Tipo_Pagamento1`
    FOREIGN KEY (`Tipo_Pagamento_Id`)
    REFERENCES `FinUp`.`Tipo_Pagamento` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Tipo_Gasto1`
    FOREIGN KEY (`Tipo_Gasto_Id`)
    REFERENCES `FinUp`.`Tipo_Gasto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_SubClasse1`
    FOREIGN KEY (`SubClasse_Id`)
    REFERENCES `FinUp`.`SubClasse` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_CNPJ1`
    FOREIGN KEY (`CNPJ_Id`)
    REFERENCES `FinUp`.`CNPJ` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Classe_Principal1`
    FOREIGN KEY (`Classe_Principal_Id`)
    REFERENCES `FinUp`.`Classe_Principal` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`Credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`Credencial` (
  `Id` INT NOT NULL ,
  `Email` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Pessoa_Fisica_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Pessoa_Fisica_Id`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  INDEX `fk_Credencial_Pessoa_Fisica_idx` (`Pessoa_Fisica_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Credencial_Pessoa_Fisica`
    FOREIGN KEY (`Pessoa_Fisica_Id`)
    REFERENCES `FinUp`.`Pessoa_Fisica` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`CNPJ_Classe_Principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`CNPJ_Classe_Principal` (
  `CNPJ_Id` INT NOT NULL,
  `Classe_Principal_Id` INT NOT NULL,
  PRIMARY KEY (`CNPJ_Id`, `Classe_Principal_Id`),
  INDEX `fk_CNPJ_has_Classe_Principal_Classe_Principal1_idx` (`Classe_Principal_Id` ASC) VISIBLE,
  INDEX `fk_CNPJ_has_Classe_Principal_CNPJ1_idx` (`CNPJ_Id` ASC) VISIBLE,
  CONSTRAINT `fk_CNPJ_has_Classe_Principal_CNPJ1`
    FOREIGN KEY (`CNPJ_Id`)
    REFERENCES `FinUp`.`CNPJ` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CNPJ_has_Classe_Principal_Classe_Principal1`
    FOREIGN KEY (`Classe_Principal_Id`)
    REFERENCES `FinUp`.`Classe_Principal` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinUp`.`SubClasse_CNPJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinUp`.`SubClasse_CNPJ` (
  `SubClasse_Id` INT NOT NULL,
  `CNPJ_Id` INT NOT NULL,
  PRIMARY KEY (`SubClasse_Id`, `CNPJ_Id`),
  INDEX `fk_SubClasse_has_CNPJ_CNPJ1_idx` (`CNPJ_Id` ASC) VISIBLE,
  INDEX `fk_SubClasse_has_CNPJ_SubClasse1_idx` (`SubClasse_Id` ASC) VISIBLE,
  CONSTRAINT `fk_SubClasse_has_CNPJ_SubClasse1`
    FOREIGN KEY (`SubClasse_Id`)
    REFERENCES `FinUp`.`SubClasse` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SubClasse_has_CNPJ_CNPJ1`
    FOREIGN KEY (`CNPJ_Id`)
    REFERENCES `FinUp`.`CNPJ` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;